server:
  port: 80
logging:
  level: debug
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.40.113.161:3306/blog
    username: maling
    password: 123456
  jpa:
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl.auto: update
      hibernate.show_sql: true
      hibernate.format_sql: true
security:
  user:
    name: admin
    password: 123456
